services:
  db:
    image: "mysql:8.0"
    volumes:
      - "./.docker/db/data:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - idsawsfnnet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: idsawsfn_db

networks:
  idsawsfnnet:
